/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE RESOURCE1

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "config.h"

#include "POUS2.h"

BOOL PLCTASK;
PROGRAM0 RESOURCE1__INSTANCE1;
#define INSTANCE1 RESOURCE1__INSTANCE1

void RESOURCE1_init__(void) {
  BOOL retain;
  retain = 0;
  
  PLCTASK = __BOOL_LITERAL(FALSE);
  PROGRAM0_init__(&INSTANCE1,retain);
}

void RESOURCE1_run__(unsigned long tick) {
  PLCTASK = !(tick % 1);
  if (PLCTASK) {
    PROGRAM0_body__(&INSTANCE1);
  }
}

